name: needle_orm
description: ORM for dart, inspired by Ebean.io (an excellent ORM from Java/Kotlin world).
version: 0.0.1
homepage: https://github.com/needle-dart/needle_orm.dart
repository: https://github.com/needle-dart/needle_orm.dart

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  inflection3: ^0.5.3+2
  recase: ^4.0.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.17.5
  needle_orm_generator: ^0.0.1
  postgres: ^2.4.1
  postgres_pool: ^2.1.3
  needle_orm_postgres: ^0.0.1
