name: needle_orm
description: Orm for Needle framework.
version: 0.0.1
homepage: https://github.com/outersky/needle_orm.dart

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  inflection3: ^0.5.3+2
  recase: ^4.0.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.17.5
